@startuml
actor Администратор
participant "Бот" as Bot

Администратор -> Bot: Нажатие "Добавить сотрудника" (кнопка)
activate Bot
Bot -> Администратор: Запрос имени нового сотрудника (сообщение)
Администратор -> Bot: Ввод имени
Bot -> Администратор: Запрос должности нового сотрудника (сообщение)
Администратор -> Bot: Ввод должности

Bot -> Администратор: Список доступных контактов в Telegram (кнопка)
Администратор -> Bot: Выбор контакта

alt Сотрудник с таким id уже существует
    Bot -> Администратор: Уведомление о существовании сотрудника (сообщение)
else Новый сотрудник
    Bot -> Администратор: Предпросмотр нового сотрудника (инлайн-кнопка подтвердить)
    Администратор -> Bot: Подтверждение добавления
    Bot -> Администратор: Уведомление об успешном добавлении сотрудника (сообщение)
end

deactivate Bot
@enduml
