@startuml
class Работник {
+ id: int (PK)
+ telegram_id : bigint
+ Имя: string
+ Должность: string
}

class Проект {
+ id: int (PK)
+ Название: string
+ Тип: enumerate
}

class Задача {
+ id: int (PK)
+ Название: string
}

class ПроектXРаботники {
+ проект_id: int (FK, PK)
+ работник_id: int (FK, PK)
}

class ПроектXЗадачи {
+ проект_id: int (FK, PK)
+ задача_id: int (FK, PK)
}

class ПроектXРаботникXЗадача {
+ id: int (PK)
+ проект_id: int (FK)
+ работник_id: int (FK)
+ задача_id: int (FK)
+ Дата: date
+ Время: double
}

Работник --* ПроектXРаботники
Проект --* ПроектXРаботники
Проект --* ПроектXЗадачи
Задача --* ПроектXЗадачи
Работник --* ПроектXРаботникXЗадача
Проект --* ПроектXРаботникXЗадача
Задача --* ПроектXРаботникXЗадача

@enduml